spring.application.name=account-service

spring.datasource.url=jdbc:mysql://localhost:3306/ridelink_account_db
spring.datasource.username=root
spring.datasource.password=Danu@20021

spring.jpa.hibernate.ddl-auto=update
jwt.secret=${RIDELINK_JWT_SECRET}
